version: "3.7"
services:
  postgresql:
    image: quay.io/redhatdemo/openshift-pgsql12-primary
    ports:
      - "5432:5432"
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: demodb
      PG_NETWORK_MASK: all
      PG_MAX_CONNECTIONS: 100
      PG_SHARED_BUFFERS: 256
      PG_WORK_MEM: 1536
      PG_EFFECTIVE_CACHE_SIZE: 1
      PG_EFFECTIVE_IO: 128
      PG_MAX_WAL_SIZE: 1
